# Github action to deploy n8n service
name: n8n Prod Deployment

on:
  push:
    paths:
      - 'n8n.Dockerfile'
      - 'copilot/n8n/**'
      - '.github/workflows/n8n-prod-deploy.yml'
    branches:
      - main
  workflow_dispatch:
  workflow_call: {}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Setup AWS CLI and Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: PROD_AWS_ROLE_TO_ASSUME
          aws-region: us-east-1

      - name: Make deployment script executable
        run: chmod +x ./scripts/copilot_service_deploy.sh

      - name: Deploy n8n Copilot Service
        run: ./scripts/copilot_service_deploy.sh $SERVICE $ENVIRONMENT
        env:
          SERVICE: n8n
          ENVIRONMENT: prod

  success:
    runs-on: ubuntu-latest
    needs:
      - deploy
    if: success()
    steps:
      - name: Success Slack Alert
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ vars.SLACK_CHANNEL_ID }}
          slack-message: ">:white_check_mark: DEPLOY TO Prod \nService: n8n \n"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  failure:
    runs-on: ubuntu-latest
    needs:
      - deploy
    if: failure()
    steps:
      - name: Failed Slack Alert
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ vars.SLACK_CHANNEL_ID }}
          slack-message: ">:x: DEPLOY TO Prod \nService: n8n \n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Failed Workflow>\n"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
